### ISSUE TITLE
打开github标签报错

### ISSUE THREAD

**Issue by JokingLove** [alibaba/ali-dbhub#13]
mac  13.1 (22C65) ，打开github 标签，报错：

![image](https://user-images.githubusercontent.com/18134074/211496413-a4cd82ca-70bf-4f9d-a410-204083ccbc89.png)

**Comment by zhuangjiaju** [comment]
已经在最新版本修复

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
