### ISSUE TITLE
Public Key Retrieval is not allowed: null

### ISSUE THREAD

**Issue by cikichen** [alibaba/ali-dbhub#175]
账号密码登录提示Public Key Retrieval is not allowed: null
<img width="683" alt="image" src="https://github.com/alibaba/Chat2DB/assets/1478821/e116421b-7344-41a9-9b6d-e7ebd6869aa0">

**Comment by yuanzhixiang** [comment]
试试在高级里面设置 allowPublicKeyRetrieval 为 true

**Comment by cikichen** [comment]
<img width="646" alt="image" src="https://github.com/alibaba/Chat2DB/assets/1478821/081dbb98-b99a-482f-b0e8-530aed3f6680">

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
