### ISSUE TITLE
SSL peer shut down incorrectly: null

### ISSUE THREAD

**Issue by nunter** [alibaba/ali-dbhub#203]
【MySQL连接】SSL peer shut down incorrectly: null

**Comment by nunter** [comment]
<img width="679" alt="image" src="https://github.com/alibaba/Chat2DB/assets/10915931/838bd0b7-3682-42b1-8933-bae46be5f21d">

**Comment by nunter** [comment]
![image](https://github.com/alibaba/Chat2DB/assets/10915931/fdaf12a1-6c36-4448-8859-a09f58f64571)

**Comment by yedong313** [comment]
这个问题解决了吗

**Comment by Nemo77763250** [comment]
这个问题解决了吗？

**Comment by nunterr** [comment]
更新到最新版，在配置添加数据库时连接后面加入useSSL=false，可以正常连接

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
