### ISSUE TITLE
Bug:MySQL 字段 bigint类型 数据展示有误

### ISSUE THREAD

**Issue by qingshanking** [alibaba/ali-dbhub#210]
MySQL 表字段 bigint类型 数据展示有误，如实际数据库不符。
![image](https://github.com/alibaba/Chat2DB/assets/22401257/9055dc34-f8a6-44cb-8cc5-63730d04bf51)

**Comment by yanxunxiaoyugan** [comment]
这个应该是js的精度问题

**Comment by shanhexi** [comment]
![image](https://github.com/alibaba/Chat2DB/assets/86969353/4d7cb600-1654-4b81-9f0f-ef8c6d6fdf98)
@jipengfei-jpf  看下，返回数据有问题

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
