### ISSUE TITLE
建议: 是否可以和navicat一样，只展示需要的数据库列表，这样数据库多的情况下可以连接成功后快速定位到自己需要的数据库

### ISSUE THREAD

**Issue by sry1201** [alibaba/ali-dbhub#227]
![image](https://github.com/alibaba/Chat2DB/assets/48204480/64b5dc73-4d72-4e4f-bd21-bbd7016450c7)
![image](https://github.com/alibaba/Chat2DB/assets/48204480/896f555c-76c0-40f5-98c9-468a6606b68e)

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
