### ISSUE TITLE
Bug: 格式化SQL前端报错

### ISSUE THREAD

**Issue by wuchuanpeng** [alibaba/ali-dbhub#283]
### Chat2DB Version

1.0.9

### Describe the bug

当Console中有不是SQL的内容并且没有注释时，虽然只选中了SQL，也会报前端错误
![20ef217121f1800822212a9dbf8fe84](https://github.com/alibaba/Chat2DB/assets/20556443/48a73be1-a482-4526-b656-bf44a8e8d198)
![72ad034a9e4f9f205b695fc47368c07](https://github.com/alibaba/Chat2DB/assets/20556443/eba6abcf-0230-401f-82df-4a3844d4bfc1)
![image](https://github.com/alibaba/Chat2DB/assets/20556443/69cb946f-0760-4126-b749-e670f271c031)

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
