### ISSUE TITLE
Bug: 自然语言转SQL的问题

### ISSUE THREAD

**Issue by netSharks** [alibaba/ali-dbhub#314]
### Chat2DB Version

1.0.10

### Describe the bug

![image](https://github.com/alibaba/Chat2DB/assets/22738221/e1cbb26c-955d-45d9-b28a-5c8a7e23a706)
1、当我选中一张表并且自动生成查询语句并选中语句时，点击自然语言转SQL，会继续提示选择表
![image](https://github.com/alibaba/Chat2DB/assets/22738221/730ef079-7222-4532-b808-052fa09f3c26)

![image](https://github.com/alibaba/Chat2DB/assets/22738221/3a090edb-0204-4f89-a448-8a8d139ec32e)
2、选择完成后解析的还是之前的语句。

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
