### ISSUE TITLE
Bug:  中文文档中下载链接无法访问OSS

### ISSUE THREAD

**Issue by wujinyiEX** [alibaba/ali-dbhub#331]
### Chat2DB Version

1.0.11

### Describe the bug

中文文档中点击下载链接
![image](https://github.com/alibaba/Chat2DB/assets/92134431/b2c906cf-13af-4d84-9d75-6f8d0442c9fb)
![image](https://github.com/alibaba/Chat2DB/assets/92134431/d30d2c02-0eb2-410a-9838-37874fc0bf7a)

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
