### ISSUE TITLE
优化: 程序运行缓慢

### ISSUE THREAD

**Issue by dzzzzz123** [alibaba/ali-dbhub#346]
感觉稍微数据大点，整个程序就会变的非常卡顿，无论是前期查询放回结果，还是前端渲染，请问是否可以优化。
这是我对比navicat的查询
![Navicat](https://github.com/alibaba/Chat2DB/assets/65523902/0f2573e1-8181-4b57-aca0-9b48e0ed3e9a)
![Chat2DB](https://github.com/alibaba/Chat2DB/assets/65523902/ec126c04-7450-4699-a848-43bc024df65e)
数据只有1000多条，但是非常慢，或者是否能提供源码的位置，我自己查看是否可以优化

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
