### ISSUE TITLE
建议: Describe demo in English so that project can be more visible

### ISSUE THREAD

**Issue by pallasite99** [alibaba/ali-dbhub#349]
* The screenshots have description in Chinese which is difficult to understand for non-native speakers

**Comment by liugddx** [comment]
This job can be left to me. @zhuangjiaju

**Comment by pallasite99** [comment]
Nice job with the functionality of the app though. Forgot to mention, but this sounds very promising.

**Comment by Chat2DB-Pro** [comment]
Chat2DB has been upgraded to version 2.0.12: has been migrated to a new repository: https://github.com/chat2db/Chat2DB

2.x new features
✨1. The AI ​​capability is upgraded, the generated content is more accurate, and it supports 100 free uses per day.
✨2. Support viewing views, triggers, functions, and stored procedures.
✨3. Support report generation, natural language generation report.
✨4. Brand new visual experience, easier to use.
🎁It will be launched in May and September, adding and editing table structures, online editing of data, generating test data, and teamwork.
Go to the new warehouse to experience Chat2DB 2.0, remember to give a star amount.
