### ISSUE TITLE
Bug: OpenAI  sse连接异常

### ISSUE THREAD

**Issue by chenhongwu127** [alibaba/ali-dbhub#369]
### Chat2DB Version

v.0.0.0

### Describe the bug

OpenAI  sse连接异常data：Invalid API key，异常：null

**Comment by lishupeng9** [comment]
me too,how to solve it?

**Comment by chenhongwu127** [comment]
openai连接的选填不写，点应用就OK



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lishupeng9 ***@***.***&gt;
发送时间: 2023年6月20日 21:50
收件人: alibaba/Chat2DB ***@***.***&gt;
抄送: chenhongwu127 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [alibaba/Chat2DB] Bug: OpenAI  sse连接异常 (Issue #369)





 
me too,how to solve it?

**Comment by websterli320** [comment]
还是不行呢？

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨1、AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨2、支持查看视图、触发器、函数、存储过程。
- ✨3、支持报表生成，自然语言生成报表。
- ✨4、全新的视觉体验，更加简单易用。
- 🎁5、9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
