### ISSUE TITLE
建议: 希望增加查询时间的显示，拓展边栏

### ISSUE THREAD

**Issue by ak289443649** [alibaba/ali-dbhub#383]
目前功能感觉很惊艳，可以丰富些功能，比如一些边栏的数据展示，我用的时间不久，感觉查询时间可以加上，会更方便让我比较生成出来的SQL和我原有的SQL执行效率的差异。

**Comment by liugddx** [comment]
> 目前功能感觉很惊艳，可以丰富些功能，比如一些边栏的数据展示，我用的时间不久，感觉查询时间可以加上，会更方便让我比较生成出来的SQL和我原有的SQL执行效率的差异。

This proposal is already underway.

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨1、AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨2、支持查看视图、触发器、函数、存储过程。
- ✨3、支持报表生成，自然语言生成报表。
- ✨4、全新的视觉体验，更加简单易用。
- 🎁5、9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
