### ISSUE TITLE
建议: TDengine Support

### ISSUE THREAD

**Issue by sangshuduo** [alibaba/ali-dbhub#395]
TDengine is an open-source and cloud-native time series database. It has gained 21k+ stars on GitHub and 255k+ installations from over 50 countries. TDengine supports SQL standards and provides a generic JDBC driver to access. 

Please let me know if you need any assistant to support TDengine. BTW, I'm from TDengine team. Thanks.

**Comment by Chat2DB-Pro** [comment]
Thank you very much for your support. It is expected that we will support TDengine in October this year. If we encounter problems with access, we hope to get your help, thank you

**Comment by sangshuduo** [comment]
> Thank you very much for your support. It is expected that we will support TDengine in October this year. If we encounter problems with access, we hope to get your help, thank you

Sue, feel free to ping me.
