### ISSUE TITLE
Bug: 当点击查询按钮之后出现弹窗

### ISSUE THREAD

**Issue by gf1023456** [alibaba/ali-dbhub#398]
### Chat2DB Version

最新windows版本

### Describe the bug

当点击查询按钮之后，出现 “系统开小差啦，请尝试刷新页面或者联系管理员” 调用接口为 http://127.0.0.1:10824/api/rdb/dml/execute 
![1687255026435](https://github.com/alibaba/Chat2DB/assets/53164796/e8ff8e6a-3616-4e18-b99c-e992a3014f1c)

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨1、AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨2、支持查看视图、触发器、函数、存储过程。
- ✨3、支持报表生成，自然语言生成报表。
- ✨4、全新的视觉体验，更加简单易用。
- 🎁5、9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e

**Comment by gf1023456** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
