### ISSUE TITLE
Bug: chatrobot按钮跑丢了

### ISSUE THREAD

**Issue by wangleigithub** [alibaba/ali-dbhub#407]
### Chat2DB Version

当前版本:v0.0.0 build 20230616055221

### Describe the bug

系统版本截图：
![1687332312233](https://github.com/alibaba/Chat2DB/assets/755879/1c2b7141-d7e0-4f60-80a7-36f5b6cb16c0)
chat2db版本截图：
![1687332242398](https://github.com/alibaba/Chat2DB/assets/755879/7d6af826-b6d1-4d88-b7cf-abedc06f9e71)
出现问题截图：
![1687332260414](https://github.com/alibaba/Chat2DB/assets/755879/2d75f5f2-14b8-4fd9-bd36-bf5ff4ce7bcb)

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨1、AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨2、支持查看视图、触发器、函数、存储过程。
- ✨3、支持报表生成，自然语言生成报表。
- ✨4、全新的视觉体验，更加简单易用。
- 🎁5、9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
