### ISSUE TITLE
建议: 是否可以提供账号验证的功能？

### ISSUE THREAD

**Issue by YaoJusheng** [alibaba/ali-dbhub#418]
虽然只是作为一个客户端连接工具，但使用docker在服务器上部署时，不希望其他团队的开发拥有操作数据库的权限，这样就需要一个账号管理功能，同时对不同账号之间的数据库连接做个隔离。

另外好像redis命令补全功能不全，有些命令无法查到，同时希望可以支持查询结果的不同解码选择并展示，如一些常见的base64,pickle等。

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨1、AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨2、支持查看视图、触发器、函数、存储过程。
- ✨3、支持报表生成，自然语言生成报表。
- ✨4、全新的视觉体验，更加简单易用。
- 🎁5、9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
