### ISSUE TITLE
Bug: SQL Server did not return a response

### ISSUE THREAD

**Issue by almightyYantao** [alibaba/ali-dbhub#425]
### Chat2DB Version

1.0.11

### Describe the bug

测试连接正常，保存后，双击打开报错，

COMMON_SYSTEM_ERROR: com.microsoft.sqlserver.jdbc.SQLServerException: SQL Server did not return a response. The connection has been closed.

![image](https://github.com/alibaba/Chat2DB/assets/34707560/a07b9e03-d53e-404a-a91d-b6714644a706)
![image](https://github.com/alibaba/Chat2DB/assets/34707560/f88f4eed-67a7-4fb9-bfef-d99a4b1395cf)

**Comment by almightyYantao** [comment]
redis也一样
![image](https://github.com/alibaba/Chat2DB/assets/34707560/b3dea846-5868-4f00-94aa-b223e3b4d9b8)

**Comment by bigsoldier** [comment]
![image](https://github.com/alibaba/ali-dbhub/assets/14001868/7ef666f8-230c-4539-8da8-4fe76d21fe3f)

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨1、AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨2、支持查看视图、触发器、函数、存储过程。
- ✨3、支持报表生成，自然语言生成报表。
- ✨4、全新的视觉体验，更加简单易用。
- 🎁5、9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
