### ISSUE TITLE
Bug: AI没有关联上线文

### ISSUE THREAD

**Issue by waterWang** [alibaba/ali-dbhub#441]
### Chat2DB Version

当前版本:v0.0.0 build 20230610114526

### Describe the bug

![image](https://github.com/alibaba/Chat2DB/assets/6082925/6f6268d7-38e2-442a-9cd8-e55fde7553e7)

mac 苹果芯片，使用你们提供的”统一代理服务“进行AI配置
步骤：
1.要求”创建一个用户表“ ，AI返回正常
2.要求”给用户表插入10条数据“，AI返回”请提供用户表的字段信息，例如：用户ID、用户名、年龄、性别等。“ 说明没有关联上线文
3.要求”给上面创建的用户表插入10条数据“，AI返回空

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表，支持数据导出。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
