### ISSUE TITLE
Bug: 我连接的是mongo数据库，自然语言中写的也是mongo数据库中的表，但是生成的sql语句还是mysql语句

### ISSUE THREAD

**Issue by yunxiaoyang01** [alibaba/ali-dbhub#446]
### Chat2DB Version

v1.0.11

### Describe the bug

--- BEGIN ---
-- 查询下列mongo数据库的表中shop_id 为'5e7dbfa6e4f3320016e9b7d1' 的结果

--- 自然语言转换 ---
SELECT * FROM shop WHERE shop_id = '5e7dbfa6e4f3320016e9b7d1'
--- END ---

**Comment by cutiyu** [comment]
目前发现的是：可以选中你的sql语句，然后选择界面上的sql转化按钮，目标数据库类型选择mongodb，就会自动转换成mongodb的语法了

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表，支持数据导出。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
