### ISSUE TITLE
Bug: database关联有问题

### ISSUE THREAD

**Issue by lan149** [alibaba/ali-dbhub#447]
### Chat2DB Version

1.0.11

### Describe the bug

![111](https://github.com/alibaba/Chat2DB/assets/8960012/6a112977-316b-417d-b03d-52cc0f5d6bc3)
请先看上面这张图，我明明已经选择好了database，右上角已经显示database名称了，但是此时去执行如图的SQL语句的时候会出现“(conn=12108352) No database selected”，这明显是选择的数据库和SQL语句没有关联上。

如果在上述截图的SQL语句里面增加如下图的database名称，才能正常运行：
![222](https://github.com/alibaba/Chat2DB/assets/8960012/9a993469-c386-4c60-b789-3f41b4b6f616)
如果如上述的，选择的database与SQL语句不能正常关联，使用起来体验性很不好，每次都需要加上database名称，希望能修复一下这个问题。

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表，支持数据导出。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
