### ISSUE TITLE
为什么我的用chatgpt报这个错误呢？

### ISSUE THREAD

**Issue by WangZhouX** [alibaba/ali-dbhub#449]
出现异常,请在帮助中查看详细日志：{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
![image](https://github.com/alibaba/Chat2DB/assets/85212356/27c8a3a4-bdb8-4e20-be43-d7c1e9122180)

**Comment by KJTM** [comment]
本地代理地址没有填

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表，支持数据导出。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
