### ISSUE TITLE
Bug: File downloaded: /root/.chat2db/jdbc-lib/hive-jdbc-3.1.2-standalone.jar 不动了

### ISSUE THREAD

**Issue by iamsboge** [alibaba/ali-dbhub#450]
### Chat2DB Version

1.0.11

### Describe the bug

执行命令：docker run --name=chat2db -p 10824:10824 chat2db/chat2db:latest
之前都正常，直到执行到最下面这一行，就卡住了，几个小时，没有反应？
File downloaded: /root/.chat2db/jdbc-lib/mariadb-java-client-3.0.8.jar
File downloaded: /root/.chat2db/jdbc-lib/mssql-jdbc-11.2.1.jre17.jar
File downloaded: /root/.chat2db/jdbc-lib/mysql-connector-java-5.1.47.jar
File downloaded: /root/.chat2db/jdbc-lib/clickhouse-jdbc-0.3.2-patch8-http.jar
File downloaded: /root/.chat2db/jdbc-lib/postgresql-42.5.1.jar
File downloaded: /root/.chat2db/jdbc-lib/mysql-connector-java-8.0.30.jar
File downloaded: /root/.chat2db/jdbc-lib/oceanbase-client-2.4.2.jar
File downloaded: /root/.chat2db/jdbc-lib/ojdbc8-19.3.0.0.jar
File downloaded: /root/.chat2db/jdbc-lib/orai18n-19.3.0.0.jar
File downloaded: /root/.chat2db/jdbc-lib/DmJdbcDriver18-8.1.2.141.jar
File downloaded: /root/.chat2db/jdbc-lib/HikariCP-4.0.3.jar
File downloaded: /root/.chat2db/jdbc-lib/redis-jdbc-driver-1.3.jar
File downloaded: /root/.chat2db/jdbc-lib/kingbase8-8.6.0.jar
File downloaded: /root/.chat2db/jdbc-lib/h2-2.1.214.jar
File downloaded: /root/.chat2db/jdbc-lib/ojdbc11.jar
File downloaded: /root/.chat2db/jdbc-lib/sqlite-jdbc-3.39.3.0.jar
File downloaded: /root/.chat2db/jdbc-lib/mongo-jdbc-standalone-1.18.jar
File downloaded: /root/.chat2db/jdbc-lib/hive-jdbc-3.1.2-standalone.jar

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表，支持数据导出。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
