### ISSUE TITLE
建议: mysql表筛选功能，视图表不展示，自然语言根据数据库类型直接转换对应的语法，可视化表结构编辑功能，redis按照文件夹格式展示

### ISSUE THREAD

**Issue by cutiyu** [alibaba/ali-dbhub#455]
1、数据库视图，可以正常查询，但是无法查看具体的表，建议支持
2、数据的列宽，建议可以通过拖拽自行调整，方便查看较长的数据，不然还要点击查看，有些情况会略显麻烦
3、自然语言转sql, 目前看是支持RDB的sql语法，其他类型存储库比如mongoDB,比如redis，虽然可以通过”SQL转化“ 生成，但是建议能直接根据当前链接的库生成，是最好的
4、配置链接的时候，指定了数据库，但是展示的时候，未重点突出当前选择的库，仍然展示的是所有的库，建议展示的时候，可以展示当前配置的数据库，同时可以切换其他库
5、建议支持表的筛选过滤
6、建议增加可视化的表结构及索引 编辑功能
7、redis按照文件夹格式展示

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
