### ISSUE TITLE
Bug: 查询不同表的相同字段时出现Bug

### ISSUE THREAD

**Issue by HumanHero** [alibaba/ali-dbhub#458]
![QQ截图20230630115220](https://github.com/alibaba/Chat2DB/assets/30451766/82575836-cbf5-46bb-a18a-09a684e829c9)
### Chat2DB Version

v0.0.0 build 20230616055221

### Describe the bug

Postgres 14

course 表
CREATE TABLE
  course (
    id integer 0 null,
    teacher_id integer 0 null,
    name character varying(254) 254 null
  );

teacher 表
CREATE TABLE
  teacher (
    id integer 0 null,
    name character varying(254) 254 null
  );

查询
SELECT course.*, teacher.name
FROM course
JOIN teacher ON course.teacher_id = teacher.id

查询结果 course.name 显示的是 teacher.name 值，其他查询工具执行该语句结果正常，course.name 起别名 course_name 或 teacher.name 起别名 teacher_name 后，显示结果正常。望修复！
![QQ截图20230630115220](https://github.com/alibaba/Chat2DB/assets/30451766/9e90c9d3-2c01-493d-a458-7fde745103b0)
![QQ截图20230630115326](https://github.com/alibaba/Chat2DB/assets/30451766/60dda4c8-d6f6-42c7-aab1-3ed9a328a777)

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
