### ISSUE TITLE
产品功能建议

### ISSUE THREAD

**Issue by zhangleijie** [alibaba/ali-dbhub#6]
目前发现只有查询功能，不能在线修改表中的数据；
希望增加如下最常用的功能：
1、在查询Tab中查询某张表后 ，在结果集中可以在线编辑然后执行生效操作。
2、右键表名时可以查看表结构，类似执行 DESC 表名。
3、右键表名时希望可以修改表结构。
4、根据查询结构可以导出 insert 语句。

**Comment by jipengfei-jpf** [comment]
感谢你的建议，我们在12月底会发布正式版本，会包含大部分功能的。

**Comment by Zach1989** [comment]
sql查询，写sql条件的时候，表字段没有自动补全功能吗？

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
