### ISSUE TITLE
历史记录中我的保存如何删除记录

### ISSUE THREAD

**Issue by k362783** [alibaba/ali-dbhub#66]

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e

**Comment by k362783** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
