### ISSUE TITLE
docker启动后访问页面，没有登录页面直接到主页面了

### ISSUE THREAD

**Issue by chenhaoqiang** [alibaba/ali-dbhub#71]
![image](https://user-images.githubusercontent.com/20062034/235175989-a00c637f-855c-4bc5-ae72-a6df6c96f436.png)
应该有团队协作功能吧，登录应该有的，不知道是我哪里没配置好

**Comment by chenhaoqiang** [comment]
![image](https://user-images.githubusercontent.com/20062034/235178403-5352c3cc-5c09-4931-8fa2-2941adf71115.png)
自己找到了，第一个版本暂未实现。

**Comment by zhuangjiaju** [comment]
这个在规划中，近期会支持

**Comment by Chat2DB-Pro** [comment]
## 📦 体验 Chat2DB
Chat2DB 已经升级至 2.0.12 版本： 已经迁移到新仓库：[https://github.com/chat2db/Chat2DB](https://github.com/chat2db/Chat2DB)

## 2.x新特性

- ✨AI能力升级，生成内容更加精准，支持每天100次的免费使用。
- ✨支持查看视图、触发器、函数、存储过程。
- ✨支持报表生成，自然语言生成报表。
- ✨全新的视觉体验，更加简单易用。
- 🎁9月份即将上线，表结构新增、编辑，数据在线编辑，生成测试数据，团队协作。

快去新仓库体验吧 [Chat2DB 2.0](https://github.com/chat2db/Chat2DB)，记得帮点个star额。

## DEMO

https://github.com/chat2db/Chat2DB/assets/22975773/79e9dded-375b-44cf-9979-bb7572465a2e
